---
  version: '3.6'
  services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
      container_name: elasticsearch-user-demo
      environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      ports:
        - "9200:9200"
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health | grep -v '\"status\":\"red\"'"]
        
    kibana:
      image: docker.elastic.co/kibana/kibana:7.6.0
      container_name: kibana-user-demo
      environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
      ports:
        - "5601:5601"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://kibana:5601/"]
      depends_on:
        - elasticsearch
    
    apm-server:
      image: docker.elastic.co/apm/apm-server:7.6.0
      container_name: apm-server-user-demo
      ports:
        - "8200:8200"
      environment:
        - output.elasticsearch.hosts=['http://elasticsearch:9200']
        - apm-server.host="0.0.0.0:8200"
        - setup.kibana.host="kibana:5601"
      command: apm-server -e -d "*" -E apm-server.host="0.0.0.0:8200" -E apm-server.expvar.enabled=true
      depends_on:
        - elasticsearch
        - kibana
      healthcheck:
        test: ["CMD", "curl", "-f" ,"http://apm-server:8200/"]
  
    mongodb-user-demo:
      image: mongo:latest
      container_name: mongodb-user-demo
      ports:
        - "27017:27017"
      expose: 
        - "27017"